export const projects = [
    {
      slug: "nana-kids-furniture-kenya",
      title: "Nana Kids Furniture Kenya",
      role: "Web Developer & SEO Specialist",
      description: "Developed a fully responsive e-commerce website for a children's furniture brand in Kenya. Implemented a complete SEO strategy to improve online visibility and drive organic traffic, leading to significant growth in customer engagement.",
      tools: ["Next.js", "React", "Node.js", "SEO Tools", "Google Analytics"],
      results: "Achieved a 200% increase in organic search traffic within the first three months and a 50% boost in online sales.",
      image: "https://placehold.co/600x400.png",
      imageHint: "kids furniture",
      tags: ["Web Developer", "Digital Marketer"],
      link: "https://nanaskidsfurniture.site/",
    },
    {
      slug: "powersparkle-australia",
      title: "Powersparkle Australia",
      role: "Digital Marketing Consultant",
      description: "Managed social media marketing campaigns and created engaging content for a cleaning services company based in Australia. Developed a targeted ad strategy to increase brand awareness and generate qualified leads.",
      tools: ["Meta Ads Manager", "Canva", "Hootsuite", "Google Analytics"],
      results: "Generated a 40% increase in lead generation through targeted social media campaigns and improved brand engagement by 60%.",
      image: "https://placehold.co/600x400.png",
      imageHint: "cleaning services",
      tags: ["Digital Marketer"],
    },
    {
      slug: "cleansparkle-kenya",
      title: "Cleansparkle Kenya",
      role: "Web & Graphic Designer",
      description: "Designed and developed a new website with an integrated booking system for a local cleaning company. Created a fresh brand identity, including a new logo and marketing materials, to enhance their market presence.",
      tools: ["Figma", "Canva", "WordPress", "Calendly"],
      results: "The new website led to a 30% increase in online bookings, and the rebrand contributed to a 25% rise in customer acquisition.",
      image: "https://placehold.co/600x400.png",
      imageHint: "sparkling clean",
      tags: ["Web Developer"],
      link: "https://cleansparkle.site/",
    },
    {
      slug: "rental-management-system",
      title: "Rental Management System",
      role: "Full-Stack Developer",
      description: "Engineered a comprehensive rental management system from the ground up. The platform features tenant and property management, automated payment processing, and maintenance request tracking to streamline operations for landlords.",
      tools: ["Next.js", "React", "Node.js", "MongoDB", "Stripe API"],
      results: "Reduced administrative tasks for property managers by 50% and improved tenant satisfaction through a centralized communication portal.",
      image: "https://placehold.co/600x400.png",
      imageHint: "property management",
      tags: ["Web Developer", "Product Manager"],
    },
    {
      slug: "shop-a-africa",
      title: "Shop a Africa E-commerce Platform",
      role: "Lead Developer",
      description: "Led the development of a multi-vendor e-commerce platform connecting African artisans with a global market. The system includes features like vendor dashboards, inventory management, and secure international payments.",
      tools: ["React", "Node.js", "Express", "PostgreSQL", "AWS S3"],
      results: "Successfully onboarded over 100 artisans in the first six months and facilitated cross-border sales to 15+ countries.",
      image: "https://placehold.co/600x400.png",
      imageHint: "ecommerce africa",
      tags: ["Web Developer", "Product Manager"],
    },
  ];