
export const projects = [
    {
      slug: "hidden-tasty-grill",
      title: "Hidden Tasty Grill",
      role: "Full-Stack Developer",
      description: "A full-stack restaurant system that includes a booking system, admin dashboard, database integration, a robust backend, and a secure payment system.",
      tools: ["Next.js", "React", "Node.js", "MongoDB", "Stripe API", "Admin Dashboard"],
      results: "Successfully launched a comprehensive restaurant management platform, improving booking efficiency by 40% and providing owners with powerful administrative tools.",
      image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxyZXN0YXVyYW50JTIwZm9vZHxlbnwwfHx8fDE3NTY3NDc1NjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "restaurant food",
      tags: ["Web Developer", "Product Manager"],
      link: "https://hotel-delta-eight.vercel.app/",
    },
    {
      slug: "nana-kids-furniture-kenya",
      title: "Nana Kids Furniture Kenya",
      role: "Web Developer & SEO Specialist",
      description: "Developed a fully responsive e-commerce website for a children's furniture brand in Kenya. Implemented a complete SEO strategy to improve online visibility and drive organic traffic, leading to significant growth in customer engagement.",
      tools: ["Next.js", "React", "Node.js", "SEO Tools", "Google Analytics"],
      results: "Achieved a 200% increase in organic search traffic within the first three months and a 50% boost in online sales.",
      image: "https://images.unsplash.com/photo-1597075958693-75173d1c837f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8a2lkcyUyMGZ1cm5pdHVyZXxlbnwwfHx8fDE3NTY3NDc1NjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "kids furniture",
      tags: ["Web Developer", "Digital Marketer"],
      link: "https://nanaskidsfurniture.site/",
    },
    {
      slug: "powersparkle-australia",
      title: "Powersparkle Australia",
      role: "Digital Marketing Consultant",
      description: "Managed social media marketing campaigns and created engaging content for a cleaning services company based in Australia. Developed a targeted ad strategy to increase brand awareness and generate qualified leads.",
      tools: ["Meta Ads Manager", "Canva", "Hootsuite", "Google Analytics"],
      results: "Generated a 40% increase in lead generation through targeted social media campaigns and improved brand engagement by 60%.",
      image: "https://images.unsplash.com/photo-1669101602124-f5b78895d91c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8Y2xlYW5pbmclMjBzZXJ2aWNlc3xlbnwwfHx8fDE3NTY3NDc1NjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "cleaning services",
      tags: ["Digital Marketer"],
    },
    {
      slug: "cleansparkle-kenya",
      title: "Cleansparkle Kenya",
      role: "Web & Graphic Designer",
      description: "Designed and developed a new website with an integrated booking system for a local cleaning company. Created a fresh brand identity, including a new logo and marketing materials, to enhance their market presence.",
      tools: ["Figma", "Canva", "WordPress", "Calendly"],
      results: "The new website led to a 30% increase in online bookings, and the rebrand contributed to a 25% rise in customer acquisition.",
      image: "https://images.unsplash.com/photo-1669831293185-370e11b4e1be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxzcGFya2xpbmclMjBjbGVhbnxlbnwwfHx8fDE3NTY3NDc1NjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "sparkling clean",
      tags: ["Web Developer"],
      link: "https://cleansparkle.site/",
    },
    {
      slug: "rental-management-system",
      title: "Rental Management System",
      role: "Full-Stack Developer",
      description: "Engineered a comprehensive rental management system from the ground up. The platform features tenant and property management, automated payment processing, and maintenance request tracking to streamline operations for landlords.",
      tools: ["Next.js", "React", "Node.js", "MongoDB", "Stripe API"],
      results: "Reduced administrative tasks for property managers by 50% and improved tenant satisfaction through a centralized communication portal.",
      image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwcm9wZXJ0eSUyMG1hbmFnZW1lbnR8ZW58MHx8fHwxNzU2NzQ3NTY0fDA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "property management",
      tags: ["Web Developer", "Product Manager"],
      link: "https://modern-christian.vercel.app/",
    },
    {
      slug: "shop-a-africa",
      title: "Shop a Africa E-commerce Platform",
      role: "Lead Developer",
      description: "Led the development of a multi-vendor e-commerce platform connecting African artisans with a global market. The system includes features like vendor dashboards, inventory management, and secure international payments.",
      tools: ["React", "Node.js", "Express", "PostgreSQL", "AWS S3"],
      results: "Successfully onboarded over 100 artisans in the first six months and facilitated cross-border sales to 15+ countries.",
      image: "https://images.unsplash.com/photo-1734255026082-82fdc81991f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxlY29tbWVyY2UlMjBhZnJpY2F8ZW58MHx8fHwxNzU2NzQ3NTYzfDA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "ecommerce africa",
      tags: ["Web Developer", "Product Manager"],
    },
    {
      slug: "sma-trent-nexus-hub",
      title: "SMA Trent Nexus Hub",
      role: "Web Developer & Digital Strategist",
      description: "Designed and developed a centralized social media hub that aggregates content from various platforms into a single, streamlined feed. This project aimed to enhance user engagement and provide a seamless content discovery experience.",
      tools: ["Next.js", "React", "Tailwind CSS", "Vercel"],
      results: "Increased user time-on-site by 40% and successfully integrated 5 different social media APIs for real-time content aggregation.",
      image: "https://images.unsplash.com/photo-1676276375742-9e3d10e39d45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxzb2NpYWwlMjBtZWRpYSUyMGh1YnxlbnwwfHx8fDE3NTY3NDc1NjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
      imageHint: "social media hub",
      tags: ["Web Developer", "Digital Marketer"],
      link: "https://sma-trent-nexus-hub.vercel.app/",
    }
  ];
